#!/bin/bash

set -eo pipefail

export TIMEFORMAT="CPU: %Us, Real: %Es"

folded() {
  echo
  echo "RUNNING: $1"
  shift
  time "$@"
}

folded "Build docs" \
  script/docs

FOM_COMMAND=_build/default/src/main/FomCommand/FomCommand.exe

run_error_examples() {
  for f in examples/errors/*.fom; do
    if $FOM_COMMAND "$f" > /dev/null; then
      echo "$f unexpectedly ran successfully"
      exit 1
    fi
  done
}

build_and_test() {
  OPTS=(--root=.)

  if [ -n "$PROFILE" ]; then
     OPTS+=(--profile "$PROFILE")
  fi

  folded "Building" \
    opam exec -- dune build "${OPTS[@]}"

  folded "Testing" \
    opam exec -- dune test "${OPTS[@]}"

  folded "Running examples" \
    $FOM_COMMAND examples/*.fom

  folded "Running error examples" \
    run_error_examples
}

if [ "$CI" = true ]; then
  PROFILE='' build_and_test
  folded "Cleaning" \
    opam exec -- dune clean
fi

PROFILE=release build_and_test

folded "Compiling examples" \
  script/compile-examples
