#!/bin/bash

# shellcheck source=common
. "${BASH_SOURCE%/*}/common"

foms=(examples/*.fom regression/*.fom)

for fom in "${foms[@]}"; do
  read -r code
  echo "$code" > "${fom%.fom}.js"
done < <($FOM_COMMAND -stop js "${foms[@]}")

for fom in "${foms[@]}"; do
  fomi="${fom%.fom}.fomi"
  $FOM_COMMAND -stop type "$fom" > "$fomi" &
done

prettier -w examples/*.js regression/*.js > /dev/null

wait
