#!/bin/bash

set -eo pipefail

build-js() {
  local TARGET="$1"
  local OUTPUT="$2"

  opam exec -- dune build --root=. --profile release "./$TARGET"

  echo "'use strict';"            > "$OUTPUT"
  cat "./_build/default/$TARGET" >> "$OUTPUT"
}

build-examples() {
  local OUTPUT=docs/examples.js

  rm -rf docs/examples
  mkdir -p docs/examples

  echo "export const examples = [" > $OUTPUT
  for example in examples/*.fom; do
    cp "$example" docs/examples/
    echo "  '$example'," >> $OUTPUT
  done
  echo "]" >> $OUTPUT

  cp -r examples/lib docs/examples/lib
  cp -r examples/errors docs/examples/errors

  rm -rf docs/regression
  mkdir -p docs/regression
  cp regression/*.fom docs/regression
}

build-examples &

build-js src/main/FomToJsRT/FomToJsRT.bc.js docs/FomToJsRT.js
build-js src/main/FomSandbox/FomSandbox.bc.js docs/FomSandbox.js

wait
