#!/bin/bash

set -eo pipefail

mkdir tmp
cd tmp

git clone git@github.com:polytypic/f-omega-mu.git
cd f-omega-mu

git checkout -b gh-pages

CI=true script/ci

rm docs/.gitignore

script/docs
if ! command -v terser > /dev/null; then
  cat << EOF

WARNING: terser not available for compressing JavaScript

EOF
else
  terser \
    -c ecma=2015 \
    -c hoist_funs \
    -c passes=3 \
    -c unsafe \
    -c unsafe_arrows \
    -c unsafe_methods \
    -c unsafe_proto \
    -m \
    -f semicolons=false \
    -o docs/FomSandbox.js -- docs/FomSandbox.js
fi

git add docs
git commit -m 'Built GitHub pages'
git push -f -u origin gh-pages

cd ../..
rm -rf tmp
