#!/bin/bash

set -eo pipefail

COMMAND="(\
  echo $'<<< <<< <<<' && \
  ./script/ci && \
  echo $'\n>>> >>> >>>' \
)"

if command -v watchexec > /dev/null; then
  watchexec --debounce 250 \
            --ignore '*.fomi' \
            --ignore '*.js' \
            --ignore '*.out' \
            --ignore docs \
            -i '_build/**' \
            -- "$COMMAND"
else
  >&2 echo "WARNING: Could not find suitable file watcher."
  exit 1
fi
